apiVersion: v1
kind: Service
metadata:
  name: teamref-service-3000
  namespace: team-reference
spec:
  selector:
    app: teamref-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

